#!/usr/bin/env bash
#
# 为 RP-26Rune 准备 Foxglove 相关的两个编译期依赖（上游仓库未随附）：
#   1) flatbuffers 25.2.10 头文件  ->  autogenerated_flatbuffers/flatbuffers/
#      原因：*_generated.h 带精确版本 static_assert，apt 的 2.0.0 不兼容。
#   2) libfoxglove.a（约 65MB）    ->  foxglove/lib/libfoxglove.a
#      原因：仓库只vendored了 C++ 包装层，底层 C 静态库需由 foxglove-sdk 快照构建。
#
# 用法：
#   ./scripts/setup_foxglove_deps.sh            # 缺什么补什么，已就绪则跳过
#   ./scripts/setup_foxglove_deps.sh --force    # 强制重建 libfoxglove.a
#   ./scripts/setup_foxglove_deps.sh --check    # 只检查，不联网、不修改文件
#
# 其余步骤（系统依赖、构建、运行）见 DEPLOY.md。

set -Eeuo pipefail

readonly FLATBUFFERS_TAG="v25.2.10"
readonly FLATBUFFERS_VERSION="25.2.10"
readonly FOXGLOVE_SDK_URL="https://github.com/foxglove/foxglove-sdk.git"
readonly FOXGLOVE_SDK_COMMIT="1f42d24640dc22ced5d21d19c971b448e750d274"
readonly FOXGLOVE_CRATE="foxglove_c"
readonly FOXGLOVE_SYMBOL="foxglove_context_new"
readonly MIN_RUST_VERSION="1.83"

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
project_root="$(cd -- "${script_dir}/.." && pwd)"

foxglove_root="${project_root}/src/core/utility/foxglove"
flatbuffers_dir="${foxglove_root}/autogenerated_flatbuffers/flatbuffers"
wrapper_source_dir="${foxglove_root}/src"
foxglove_lib="${foxglove_root}/lib/libfoxglove.a"

mode="install"
work_dir=""

log()
{
    printf '\n[foxglove-deps] %s\n' "$*"
}

die()
{
    printf '[foxglove-deps] ERROR: %s\n' "$*" >&2
    exit 1
}

usage()
{
    cat <<'EOF'
Usage:
  ./scripts/setup_foxglove_deps.sh           Install missing Foxglove build dependencies
  ./scripts/setup_foxglove_deps.sh --force   Rebuild libfoxglove.a even if it already exists
  ./scripts/setup_foxglove_deps.sh --check   Verify only; no network access, no file changes
  ./scripts/setup_foxglove_deps.sh --help    Show this help

Dependencies prepared:
  flatbuffers 25.2.10 headers  ->  src/core/utility/foxglove/autogenerated_flatbuffers/flatbuffers
  libfoxglove.a                ->  src/core/utility/foxglove/lib/libfoxglove.a

libfoxglove.a is built from foxglove-sdk with cargo, so the first run needs network
access to github.com and crates.io, plus a Rust toolchain (rustup is installed
automatically when cargo is missing).
EOF
}

cleanup()
{
    if [[ -n "${work_dir}" && -d "${work_dir}" ]]; then
        rm -rf -- "${work_dir}"
    fi
}

for argument in "$@"; do
    case "${argument}" in
        --force)
            mode="force"
            ;;
        --check)
            mode="check"
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            usage >&2
            die "unknown argument: ${argument}"
            ;;
    esac
done

trap cleanup EXIT

require_command()
{
    command -v "$1" >/dev/null 2>&1 || die "missing command: $1"
}

version_greater_or_equal()
{
    # $1: candidate, $2: minimum
    # 不要用 head -n1：它提前退出会让 sort 收到 SIGPIPE，在 pipefail 下被误判为失败
    local lowest
    lowest="$(printf '%s\n%s\n' "$2" "$1" | sort -V | sed -n '1p')"
    [[ "${lowest}" == "$2" ]]
}

installed_flatbuffers_version()
{
    local base_header="${flatbuffers_dir}/base.h"
    [[ -r "${base_header}" ]] || return 1

    local major minor revision
    major="$(awk '/define FLATBUFFERS_VERSION_MAJOR/{print $3; exit}' "${base_header}")"
    minor="$(awk '/define FLATBUFFERS_VERSION_MINOR/{print $3; exit}' "${base_header}")"
    revision="$(awk '/define FLATBUFFERS_VERSION_REVISION/{print $3; exit}' "${base_header}")"
    [[ -n "${major}" && -n "${minor}" && -n "${revision}" ]] || return 1

    printf '%s.%s.%s' "${major}" "${minor}" "${revision}"
}

check_flatbuffers()
{
    local installed_version
    installed_version="$(installed_flatbuffers_version)" ||
        die "flatbuffers headers are missing: ${flatbuffers_dir} (run without --check)"

    [[ "${installed_version}" == "${FLATBUFFERS_VERSION}" ]] ||
        die "flatbuffers version mismatch: found ${installed_version}, need ${FLATBUFFERS_VERSION}"

    log "flatbuffers ${installed_version}: OK (${flatbuffers_dir})"
}

check_foxglove_lib()
{
    [[ -s "${foxglove_lib}" ]] ||
        die "libfoxglove.a is missing: ${foxglove_lib} (run without --check)"

    require_command nm
    # 不要用 grep -q：它提前退出会让 nm 收到 SIGPIPE，在 pipefail 下被误判为失败
    nm -g --defined-only "${foxglove_lib}" 2>/dev/null | grep -w "${FOXGLOVE_SYMBOL}" >/dev/null ||
        die "libfoxglove.a does not define ${FOXGLOVE_SYMBOL}; rebuild with --force"

    log "libfoxglove.a: OK ($(du -h "${foxglove_lib}" | cut -f1), defines ${FOXGLOVE_SYMBOL})"
}

install_flatbuffers()
{
    local installed_version
    if installed_version="$(installed_flatbuffers_version)"; then
        if [[ "${installed_version}" == "${FLATBUFFERS_VERSION}" ]]; then
            log "flatbuffers ${installed_version} already present; skipping download"
            return 0
        fi
        log "flatbuffers ${installed_version} found; replacing with ${FLATBUFFERS_VERSION}"
    fi

    log "Downloading flatbuffers ${FLATBUFFERS_TAG} headers"
    require_command git
    git clone --quiet --depth 1 --branch "${FLATBUFFERS_TAG}" \
        https://github.com/google/flatbuffers.git "${work_dir}/flatbuffers"

    [[ -d "${work_dir}/flatbuffers/include/flatbuffers" ]] ||
        die "unexpected flatbuffers layout: include/flatbuffers not found"

    # 先删除再复制：直接覆盖会残留旧版本中已不存在的头文件
    rm -rf -- "${flatbuffers_dir}"
    mkdir -p -- "$(dirname -- "${flatbuffers_dir}")"
    cp -r -- "${work_dir}/flatbuffers/include/flatbuffers" "${flatbuffers_dir}"

    check_flatbuffers
}

install_rust()
{
    if command -v cargo >/dev/null 2>&1; then
        return 0
    fi

    log "Installing the Rust toolchain via rustup (minimal profile)"
    if [[ -z "${RUSTUP_DIST_SERVER:-}" ]]; then
        log "Tip: if static.rust-lang.org is unreachable or very slow, use a mirror first, e.g."
        log "     export RUSTUP_DIST_SERVER=https://mirrors.tuna.tsinghua.edu.cn/rustup"
        log "     export RUSTUP_UPDATE_ROOT=https://mirrors.tuna.tsinghua.edu.cn/rustup/rustup"
    fi
    require_command curl
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs |
        sh -s -- -y --profile minimal --no-modify-path

    # shellcheck disable=SC1091
    [[ -f "${CARGO_HOME:-${HOME}/.cargo}/env" ]] && source "${CARGO_HOME:-${HOME}/.cargo}/env"
    export PATH="${CARGO_HOME:-${HOME}/.cargo}/bin:${PATH}"
}

check_rust()
{
    install_rust
    command -v cargo >/dev/null 2>&1 || die "cargo is still unavailable after rustup install"

    local rust_version
    rust_version="$(rustc --version | awk '{print $2}')"
    version_greater_or_equal "${rust_version}" "${MIN_RUST_VERSION}" ||
        die "rustc ${rust_version} is too old; foxglove-sdk requires >= ${MIN_RUST_VERSION}"

    log "Rust ${rust_version}: OK"
}

verify_wrapper_snapshot()
{
    local sdk_dir="$1"
    local file
    local mismatch=0

    for file in context.cpp mcap.cpp server.cpp; do
        [[ -f "${wrapper_source_dir}/${file}" ]] || continue
        if ! git -C "${sdk_dir}" show "${FOXGLOVE_SDK_COMMIT}:cpp/foxglove/src/${file}" 2>/dev/null |
            diff -q - "${wrapper_source_dir}/${file}" >/dev/null; then
            mismatch=1
        fi
    done

    if (( mismatch )); then
        log "WARNING: vendored foxglove C++ wrapper no longer matches foxglove-sdk"
        log "         ${FOXGLOVE_SDK_COMMIT:0:8}; the C ABI may have changed."
        log "         Re-derive the matching snapshot commit before trusting this build."
    else
        log "foxglove C++ wrapper matches foxglove-sdk ${FOXGLOVE_SDK_COMMIT:0:8}"
    fi
}

install_foxglove_lib()
{
    if [[ -s "${foxglove_lib}" && "${mode}" != "force" ]]; then
        log "libfoxglove.a already present ($(du -h "${foxglove_lib}" | cut -f1)); use --force to rebuild"
        return 0
    fi

    check_rust
    require_command git
    require_command nm

    log "Fetching foxglove-sdk snapshot ${FOXGLOVE_SDK_COMMIT:0:8}"
    git clone --quiet --depth 1 "${FOXGLOVE_SDK_URL}" "${work_dir}/foxglove-sdk"
    git -C "${work_dir}/foxglove-sdk" fetch --quiet --unshallow
    if ! git -C "${work_dir}/foxglove-sdk" checkout --quiet "${FOXGLOVE_SDK_COMMIT}"; then
        git -C "${work_dir}/foxglove-sdk" fetch --quiet --depth 1 origin "${FOXGLOVE_SDK_COMMIT}"
        git -C "${work_dir}/foxglove-sdk" checkout --quiet FETCH_HEAD
    fi

    verify_wrapper_snapshot "${work_dir}/foxglove-sdk"

    # aws-lc-sys 的 bindgen 需要 C 标准库头文件；系统 clang 缺少 resource dir 时会找不到 stddef.h
    if [[ -z "${BINDGEN_EXTRA_CLANG_ARGS:-}" ]]; then
        local cc_include
        cc_include="$(gcc -print-file-name=include 2>/dev/null || true)"
        [[ -d "${cc_include}" ]] || cc_include="$(cc -print-file-name=include 2>/dev/null || true)"
        if [[ -d "${cc_include}" ]]; then
            export BINDGEN_EXTRA_CLANG_ARGS="-I${cc_include}"
            log "BINDGEN_EXTRA_CLANG_ARGS=${BINDGEN_EXTRA_CLANG_ARGS}"
        fi
    fi

    log "Building ${FOXGLOVE_CRATE} with cargo (first run downloads crates and takes a few minutes)"
    cargo build --release --manifest-path "${work_dir}/foxglove-sdk/Cargo.toml" -p "${FOXGLOVE_CRATE}"

    local built_archive="${work_dir}/foxglove-sdk/target/release/libfoxglove.a"
    [[ -s "${built_archive}" ]] || die "cargo finished but ${built_archive} is missing"

    nm -g --defined-only "${built_archive}" 2>/dev/null | grep -w "${FOXGLOVE_SYMBOL}" >/dev/null ||
        die "built archive does not define ${FOXGLOVE_SYMBOL}"

    mkdir -p -- "$(dirname -- "${foxglove_lib}")"
    cp -f -- "${built_archive}" "${foxglove_lib}"

    check_foxglove_lib
}

if [[ "${mode}" == "check" ]]; then
    log "Checking Foxglove build dependencies of ${project_root}"
    check_flatbuffers
    check_foxglove_lib
    log "Environment check passed"
    exit 0
fi

work_dir="$(mktemp -d)"

log "Preparing Foxglove build dependencies of ${project_root}"
install_flatbuffers
install_foxglove_lib

log "Done. Next steps:"
printf '  cmake -S %q -B %q -DCMAKE_BUILD_TYPE=Release\n' "${project_root}" "${project_root}/build"
printf '  cmake --build %q --parallel "$(nproc)"\n' "${project_root}/build"
printf '  %q\n' "${project_root}/run_demo.sh"
